package com.example.soundscape;

import net.minecraft.client.MinecraftClient;
import net.minecraft.registry.RegistryKey;
import net.minecraft.sound.SoundEvent;
import net.minecraft.util.Identifier;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.biome.BiomeKeys;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;

/**
 * BiomeMusicHandler
 *
 * Maps each Minecraft biome to a music genre.
 * Genre assignments mirror the world profiles generated by the
 * Soundscape seed tool — so the music you hear reflects the song
 * that created the world.
 *
 * Genre → Biome logic (mirrors seed-generator/main.py):
 *   metal      → Nether biomes, Deep Dark        (high energy, minor mode)
 *   indipop    → Cherry Grove, Pale Garden        (high valence, acoustic)
 *   country    → Pale Garden, Windswept biomes    (acoustic, moderate valence)
 *   ambient    → Old Growth, Swamp, Lush Caves    (high acousticness)
 *   electronic → Badlands, Savanna                (high danceability)
 *   jazz       → Meadow, Flower Forest, Sunflower (bright keys C/F/G)
 *   default    → Everything else
 */
public class BiomeMusicHandler {

    private static String currentGenre = null;
    private static LoopingSoundInstance currentSound = null;
    private static final Random RANDOM = new Random();

    // ---------------------------------------------------------------
    // Genre → track list  (add more tracks per genre as you like)
    // ---------------------------------------------------------------
    private static final Map<String, String[]> GENRE_TRACKS = new HashMap<>();

    static {
        GENRE_TRACKS.put("metal", new String[]{
            "soundscape:metal.track1",
            "soundscape:metal.track2"
        });
        GENRE_TRACKS.put("indipop", new String[]{
            "soundscape:indipop.track1",
            "soundscape:indipop.track2"
        });
        GENRE_TRACKS.put("country", new String[]{
            "soundscape:country.track1",
            "soundscape:country.track2"
        });
        GENRE_TRACKS.put("ambient", new String[]{
            "soundscape:ambient.track1",
            "soundscape:ambient.track2"
        });
        GENRE_TRACKS.put("electronic", new String[]{
            "soundscape:electronic.track1",
            "soundscape:electronic.track2"
        });
        GENRE_TRACKS.put("jazz", new String[]{
            "soundscape:jazz.track1",
            "soundscape:jazz.track2"
        });
        GENRE_TRACKS.put("default", new String[]{
            "soundscape:default.track1"
        });
    }

    // ---------------------------------------------------------------
    // Biome → genre mapping
    // ---------------------------------------------------------------
    private static final Map<RegistryKey<Biome>, String> BIOME_GENRE_MAP = new HashMap<>();

    static {

        // === METAL — Nether + Deep Dark ===
        BIOME_GENRE_MAP.put(BiomeKeys.NETHER_WASTES,      "metal");
        BIOME_GENRE_MAP.put(BiomeKeys.SOUL_SAND_VALLEY,   "metal");
        BIOME_GENRE_MAP.put(BiomeKeys.CRIMSON_FOREST,     "metal");
        BIOME_GENRE_MAP.put(BiomeKeys.WARPED_FOREST,      "metal");
        BIOME_GENRE_MAP.put(BiomeKeys.BASALT_DELTAS,      "metal");
        BIOME_GENRE_MAP.put(BiomeKeys.DEEP_DARK,          "metal");

        // === INDIE POP — soft, dreamy biomes ===
        BIOME_GENRE_MAP.put(BiomeKeys.CHERRY_GROVE,       "indipop");
        BIOME_GENRE_MAP.put(BiomeKeys.PALE_GARDEN,        "indipop");

        // === COUNTRY — wild, open, natural ===
        BIOME_GENRE_MAP.put(BiomeKeys.WINDSWEPT_HILLS,         "country");
        BIOME_GENRE_MAP.put(BiomeKeys.WINDSWEPT_GRAVELLY_HILLS,"country");
        BIOME_GENRE_MAP.put(BiomeKeys.WINDSWEPT_FOREST,        "country");
        BIOME_GENRE_MAP.put(BiomeKeys.WINDSWEPT_SAVANNA,       "country");
        BIOME_GENRE_MAP.put(BiomeKeys.STONY_PEAKS,             "country");
        BIOME_GENRE_MAP.put(BiomeKeys.JAGGED_PEAKS,            "country");
        BIOME_GENRE_MAP.put(BiomeKeys.FROZEN_PEAKS,            "country");
        BIOME_GENRE_MAP.put(BiomeKeys.SNOWY_SLOPES,            "country");

        // === AMBIENT — dense, old, atmospheric ===
        BIOME_GENRE_MAP.put(BiomeKeys.OLD_GROWTH_BIRCH_FOREST, "ambient");
        BIOME_GENRE_MAP.put(BiomeKeys.OLD_GROWTH_PINE_TAIGA,   "ambient");
        BIOME_GENRE_MAP.put(BiomeKeys.OLD_GROWTH_SPRUCE_TAIGA, "ambient");
        BIOME_GENRE_MAP.put(BiomeKeys.DARK_FOREST,             "ambient");
        BIOME_GENRE_MAP.put(BiomeKeys.SWAMP,                   "ambient");
        BIOME_GENRE_MAP.put(BiomeKeys.MANGROVE_SWAMP,          "ambient");
        BIOME_GENRE_MAP.put(BiomeKeys.LUSH_CAVES,              "ambient");
        BIOME_GENRE_MAP.put(BiomeKeys.DRIPSTONE_CAVES,         "ambient");
        BIOME_GENRE_MAP.put(BiomeKeys.MUSHROOM_FIELDS,         "ambient");
        BIOME_GENRE_MAP.put(BiomeKeys.END_MIDLANDS,            "ambient");
        BIOME_GENRE_MAP.put(BiomeKeys.END_HIGHLANDS,           "ambient");
        BIOME_GENRE_MAP.put(BiomeKeys.END_BARRENS,             "ambient");
        BIOME_GENRE_MAP.put(BiomeKeys.THE_VOID,                "ambient");
        BIOME_GENRE_MAP.put(BiomeKeys.SMALL_END_ISLANDS,       "ambient");

        // === ELECTRONIC — hot, energetic, open ===
        BIOME_GENRE_MAP.put(BiomeKeys.BADLANDS,                "electronic");
        BIOME_GENRE_MAP.put(BiomeKeys.ERODED_BADLANDS,         "electronic");
        BIOME_GENRE_MAP.put(BiomeKeys.WOODED_BADLANDS,         "electronic");
        BIOME_GENRE_MAP.put(BiomeKeys.SAVANNA,                 "electronic");
        BIOME_GENRE_MAP.put(BiomeKeys.SAVANNA_PLATEAU,         "electronic");
        BIOME_GENRE_MAP.put(BiomeKeys.DESERT,                  "electronic");

        // === JAZZ — cheerful, bright, lively ===
        BIOME_GENRE_MAP.put(BiomeKeys.MEADOW,                  "jazz");
        BIOME_GENRE_MAP.put(BiomeKeys.FLOWER_FOREST,           "jazz");
        BIOME_GENRE_MAP.put(BiomeKeys.SUNFLOWER_PLAINS,        "jazz");
        BIOME_GENRE_MAP.put(BiomeKeys.JUNGLE,                  "jazz");
        BIOME_GENRE_MAP.put(BiomeKeys.SPARSE_JUNGLE,           "jazz");
        BIOME_GENRE_MAP.put(BiomeKeys.BAMBOO_JUNGLE,           "jazz");
        BIOME_GENRE_MAP.put(BiomeKeys.BEACH,                   "jazz");
        BIOME_GENRE_MAP.put(BiomeKeys.STONY_SHORE,             "jazz");

        // default covers: plains, forest, taiga, ocean, river, etc.
    }

    // ---------------------------------------------------------------

    public static void onBiomeChanged(MinecraftClient client, RegistryKey<Biome> biomeKey) {
        String genre = BIOME_GENRE_MAP.getOrDefault(biomeKey, "default");

        // Already playing this genre and track hasn't finished — do nothing
        if (genre.equals(currentGenre) && currentSound != null && !currentSound.isDone()) {
            return;
        }

        stopCurrentMusic(client);

        // Pick a random track from the genre pool
        String[] tracks  = GENRE_TRACKS.getOrDefault(genre, GENRE_TRACKS.get("default"));
        String chosenTrack = tracks[RANDOM.nextInt(tracks.length)];

        SoundEvent soundEvent = SoundEvent.of(Identifier.of(chosenTrack));
        currentSound = new LoopingSoundInstance(soundEvent, 0.5f, 1.0f);
        client.getSoundManager().play(currentSound);

        currentGenre = genre;
        System.out.println("[Soundscape] Biome: " + biomeKey.getValue()
            + " → Genre: " + genre + " → Track: " + chosenTrack);
    }

    public static void stopCurrentMusic(MinecraftClient client) {
        if (currentSound != null) {
            client.getSoundManager().stop(currentSound);
            currentSound = null;
        }
        currentGenre = null;
    }

    public static boolean isPlayingCustomMusic() {
        return currentSound != null && !currentSound.isDone();
    }
}
